# Generated by Django 3.2.4 on 2021-06-20 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='expiry_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 14, 58, 49, 69881)),
            preserve_default=False,
        ),
    ]
